### ISSUE TITLE
setting enforced options

### ISSUE THREAD

**Issue by jac18281828** [stader-labs/ethx_oft#6]
[stargate](https://stargate.finance) requires OFT to use enforced options

- add enforced options to the oft
- deploy an upgraded OFT

The main option currently in use is `ExecutorLzReceiveOption`.  Gas should be enforced to 200_000

**Comment by jac18281828** [comment]
[setting-enforced-options](https://docs.layerzero.network/v2/developers/evm/oft/quickstart#setting-enforced-options)

**Comment by blockgroot** [comment]
https://etherscan.io/tx/0x38b96cf7181c9938610be03e60becad2adabda2e04bf0bffabe4ecd107ab9a5f
